//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma.pages.Cobranza
{


    public partial class Folios
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// txtUsuario control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField txtUsuario;

        /// <summary>
        /// txtIdTipoUsuario control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField txtIdTipoUsuario;

        /// <summary>
        /// txtIdUsuario control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField txtIdUsuario;
    }
}
