//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class activo
    {
        public int id_activo { get; set; }
        public string tipo { get; set; }
        public string descripcion { get; set; }
        public string numero_serie { get; set; }
        public Nullable<double> costo { get; set; }
        public string comentarios { get; set; }
        public Nullable<int> eliminado { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_categoria { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual categoria categoria { get; set; }
    }
}
