//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria
    {
        public categoria()
        {
            this.activo1 = new HashSet<activo>();
            this.material_entrega = new HashSet<material_entrega>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<int> eliminado { get; set; }
        public Nullable<int> es_material_entrega { get; set; }
    
        public virtual ICollection<activo> activo1 { get; set; }
        public virtual ICollection<material_entrega> material_entrega { get; set; }
    }
}
