//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.prestamo = new HashSet<prestamo>();
        }
    
        public int id_cliente { get; set; }
        public string curp { get; set; }
        public string nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string ocupacion { get; set; }
        public string telefono { get; set; }
        public Nullable<int> id_tipo_cliente { get; set; }
        public string curp_aval { get; set; }
        public string nombre_aval { get; set; }
        public string primer_apellido_aval { get; set; }
        public string segundo_apellido_aval { get; set; }
        public string ocupacion_aval { get; set; }
        public string telefono_aval { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<int> eliminado { get; set; }
        public Nullable<int> id_status_cliente { get; set; }
        public string nota_fotografia { get; set; }
        public string nota_fotografia_aval { get; set; }
    
        public virtual tipo_cliente tipo_cliente { get; set; }
        public virtual ICollection<prestamo> prestamo { get; set; }
    }
}
