//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracion
    {
        public int id_configuracion { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha_ultima_modificacion { get; set; }
        public Nullable<double> valor { get; set; }
        public string ValorCadena { get; set; }
    }
}
