//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class direccion
    {
        public int id_direccion { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_aval { get; set; }
        public string calleyno { get; set; }
        public string colonia { get; set; }
        public string municipio { get; set; }
        public string estado { get; set; }
        public string telefono { get; set; }
        public string codigo_postal { get; set; }
        public Nullable<int> id_municipio { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<int> aval { get; set; }
        public string direccion_trabajo { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string ubicacion { get; set; }
    }
}
