//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        public int id_documento_colaborador { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_tipo_documento { get; set; }
        public string contenido { get; set; }
        public Nullable<int> eliminado { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_aval { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string extension { get; set; }
    }
}
