//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public empleado()
        {
            this.activo1 = new HashSet<activo>();
            this.material_entrega = new HashSet<material_entrega>();
            this.usuario = new HashSet<usuario>();
        }
    
        public int id_empleado { get; set; }
        public Nullable<int> id_tipo_usuario { get; set; }
        public Nullable<int> id_comision_inicial { get; set; }
        public Nullable<int> id_posicion { get; set; }
        public Nullable<int> id_plaza { get; set; }
        public string curp { get; set; }
        public string email { get; set; }
        public string nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string telefono { get; set; }
        public Nullable<int> eliminado { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<int> id_supervisor { get; set; }
        public Nullable<int> id_ejecutivo { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public string nombre_aval { get; set; }
        public string primer_apellido_aval { get; set; }
        public string segundo_apellido_aval { get; set; }
        public string curp_aval { get; set; }
        public string telefono_aval { get; set; }
        public Nullable<double> monto_limite_inicial { get; set; }
        public Nullable<int> id_coordinador { get; set; }
    
        public virtual ICollection<activo> activo1 { get; set; }
        public virtual ICollection<material_entrega> material_entrega { get; set; }
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
