//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class garantia_prestamo
    {
        public int id_garantia_prestamo { get; set; }
        public Nullable<int> id_prestamo { get; set; }
        public string nombre { get; set; }
        public string numero_serie { get; set; }
        public Nullable<double> costo { get; set; }
        public string fotografia { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> aval { get; set; }
        public Nullable<int> eliminado { get; set; }
    }
}
