//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_cliente
    {
        public int id_historial_cliente { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_semana { get; set; }
        public Nullable<int> atiempo { get; set; }
        public Nullable<int> abonado { get; set; }
        public Nullable<int> falla { get; set; }
    }
}
