//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class inversion
    {
        public int id_inversion { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_inversionista { get; set; }
        public Nullable<int> eliminado { get; set; }
        public string comprobante { get; set; }
        public Nullable<int> id_periodo { get; set; }
        public Nullable<int> utilidades { get; set; }
        public Nullable<int> retiro_efectuado { get; set; }
    
        public virtual inversionista inversionista { get; set; }
        public virtual periodo periodo { get; set; }
    }
}
