//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class inversion_total
    {
        public int id_inversion_total { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<double> monto_total { get; set; }
        public Nullable<int> id_inversionista { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    }
}
