//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class inversionista
    {
        public inversionista()
        {
            this.inversion = new HashSet<inversion>();
        }
    
        public int id_inversionista { get; set; }
        public string nombre { get; set; }
        public string razon_social { get; set; }
        public string rfc { get; set; }
        public Nullable<int> eliminado { get; set; }
        public Nullable<double> porcentaje_interes_anual { get; set; }
    
        public virtual ICollection<inversion> inversion { get; set; }
    }
}
