//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class material_entrega
    {
        public int id_material_entrega { get; set; }
        public string material_entregado { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<double> costo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> eliminado { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual empleado empleado { get; set; }
    }
}
