//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sendaquetzalv1Entitiesv1 : DbContext
    {
        public sendaquetzalv1Entitiesv1()
            : base("name=sendaquetzalv1Entitiesv1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<abono_pago> abono_pago { get; set; }
        public DbSet<activo> activo { get; set; }
        public DbSet<calendario> calendario { get; set; }
        public DbSet<categoria> categoria { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<comision> comision { get; set; }
        public DbSet<configuracion> configuracion { get; set; }
        public DbSet<dias_paro> dias_paro { get; set; }
        public DbSet<direccion> direccion { get; set; }
        public DbSet<documento> documento { get; set; }
        public DbSet<empleado> empleado { get; set; }
        public DbSet<evaluacion_colaborador> evaluacion_colaborador { get; set; }
        public DbSet<forma_pago> forma_pago { get; set; }
        public DbSet<garantia_prestamo> garantia_prestamo { get; set; }
        public DbSet<gasto> gasto { get; set; }
        public DbSet<historial_cliente> historial_cliente { get; set; }
        public DbSet<inversion> inversion { get; set; }
        public DbSet<inversion_movimiento> inversion_movimiento { get; set; }
        public DbSet<inversion_retiro> inversion_retiro { get; set; }
        public DbSet<inversion_total> inversion_total { get; set; }
        public DbSet<inversionista> inversionista { get; set; }
        public DbSet<log_cambios> log_cambios { get; set; }
        public DbSet<material_entrega> material_entrega { get; set; }
        public DbSet<modulo> modulo { get; set; }
        public DbSet<pago> pago { get; set; }
        public DbSet<periodo> periodo { get; set; }
        public DbSet<permisos> permisos { get; set; }
        public DbSet<permisos_tipo_usuario> permisos_tipo_usuario { get; set; }
        public DbSet<plantilla> plantilla { get; set; }
        public DbSet<plaza> plaza { get; set; }
        public DbSet<prestamo> prestamo { get; set; }
        public DbSet<regla_evaluacion_modulo> regla_evaluacion_modulo { get; set; }
        public DbSet<relacion_prestamo_aprobacion> relacion_prestamo_aprobacion { get; set; }
        public DbSet<reporte> reporte { get; set; }
        public DbSet<resumen_calculo_fallas> resumen_calculo_fallas { get; set; }
        public DbSet<solicitud_aumento_credito> solicitud_aumento_credito { get; set; }
        public DbSet<status_cliente> status_cliente { get; set; }
        public DbSet<status_pago> status_pago { get; set; }
        public DbSet<status_prestamo> status_prestamo { get; set; }
        public DbSet<status_solicitud_aumento_credito> status_solicitud_aumento_credito { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tipo_cliente> tipo_cliente { get; set; }
        public DbSet<tipo_documento> tipo_documento { get; set; }
        public DbSet<tipo_movimiento_inversion> tipo_movimiento_inversion { get; set; }
        public DbSet<tipo_paro> tipo_paro { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<web_pregunta_frecuente> web_pregunta_frecuente { get; set; }
        public DbSet<frecuencia_envio_mensaje> frecuencia_envio_mensaje { get; set; }
        public DbSet<posicion> posicion { get; set; }
        public DbSet<tipo_plantilla> tipo_plantilla { get; set; }
        public DbSet<web_acercade> web_acercade { get; set; }
        public DbSet<web_politicas_privacidad> web_politicas_privacidad { get; set; }
        public DbSet<web_terminos_condiciones> web_terminos_condiciones { get; set; }
        public DbSet<web_tutorial> web_tutorial { get; set; }
    }
}
