//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        public int id_pago { get; set; }
        public Nullable<int> id_prestamo { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<double> saldo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_status_pago { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fecha_registro_pago { get; set; }
        public Nullable<int> numero_semana { get; set; }
        public Nullable<double> pagado { get; set; }
        public Nullable<int> semana_extra { get; set; }
        public Nullable<int> pagado_con_adelanto { get; set; }
        public Nullable<int> id_prestamo_adelanto { get; set; }
        public Nullable<int> es_recuperado { get; set; }
    }
}
