//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisos
    {
        public int id_permiso { get; set; }
        public string nombre { get; set; }
        public Nullable<int> tipo_permiso { get; set; }
        public Nullable<bool> activo { get; set; }
        public string nombre_interno { get; set; }
        public string nombre_recurso { get; set; }
        public Nullable<int> id_tipo_usuario { get; set; }
    }
}
