//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantilla
    {
        public int id { get; set; }
        public string contenido { get; set; }
        public Nullable<int> id_tipo_plantilla { get; set; }
        public Nullable<int> id_frecuencia_envio_mensaje { get; set; }
        public Nullable<int> eliminado { get; set; }
        public string nombre { get; set; }
    }
}
