//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class posicion
    {
        public int id_posicion { get; set; }
        public string nombre { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<int> eliminado { get; set; }
        public string pagina_entrada { get; set; }
    }
}
