//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class prestamo
    {
        public prestamo()
        {
            this.solicitud_aumento_credito = new HashSet<solicitud_aumento_credito>();
        }
    
        public int id_prestamo { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<int> id_status_prestamo { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string notas_generales { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion { get; set; }
        public Nullable<double> monto_con_interes { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual status_prestamo status_prestamo { get; set; }
        public virtual ICollection<solicitud_aumento_credito> solicitud_aumento_credito { get; set; }
    }
}
