//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class regla_evaluacion_modulo
    {
        public int id_regla_evaluacion_modulo { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> ponderacion { get; set; }
        public Nullable<int> id_comision { get; set; }
        public Nullable<int> eliminado { get; set; }
    }
}
