//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class relacion_prestamo_aprobacion
    {
        public int id_historial_aprobacion { get; set; }
        public Nullable<int> id_prestamo { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_supervisor { get; set; }
        public Nullable<int> id_ejecutivo { get; set; }
        public string notas_aval { get; set; }
        public string notas_cliente { get; set; }
        public Nullable<int> id_posicion { get; set; }
        public string status_aprobacion { get; set; }
        public string notas_generales { get; set; }
    }
}
