//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporte
    {
        public int id_reporte { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string contenido { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_tipo_reporte { get; set; }
    }
}
