//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class status_prestamo
    {
        public status_prestamo()
        {
            this.prestamo = new HashSet<prestamo>();
        }
    
        public int id_status_prestamo { get; set; }
        public string nombre { get; set; }
        public string color { get; set; }
    
        public virtual ICollection<prestamo> prestamo { get; set; }
    }
}
