//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class status_solicitud_aumento_credito
    {
        public status_solicitud_aumento_credito()
        {
            this.solicitud_aumento_credito = new HashSet<solicitud_aumento_credito>();
        }
    
        public int id_status_solicitud_aumento_credito { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<solicitud_aumento_credito> solicitud_aumento_credito { get; set; }
    }
}
