//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_cliente
    {
        public tipo_cliente()
        {
            this.cliente = new HashSet<cliente>();
        }
    
        public int id_tipo_cliente { get; set; }
        public string tipo_cliente1 { get; set; }
        public Nullable<double> prestamo_inicial_maximo { get; set; }
        public Nullable<double> porcentaje_semanal { get; set; }
        public Nullable<int> semanas_a_prestar { get; set; }
        public Nullable<double> garantias_por_monto { get; set; }
        public string fechas_pago { get; set; }
        public Nullable<double> cantidad_para_renovar { get; set; }
        public Nullable<int> semana_extra { get; set; }
        public Nullable<int> eliminado { get; set; }
        public Nullable<int> fecha_pago_lunes { get; set; }
        public Nullable<int> fecha_pago_martes { get; set; }
        public Nullable<int> fecha_pago_miercoles { get; set; }
        public Nullable<int> fecha_pago_jueves { get; set; }
        public Nullable<int> fecha_pago_viernes { get; set; }
        public Nullable<int> fecha_pago_sabado { get; set; }
        public Nullable<int> fecha_pago_domingo { get; set; }
    
        public virtual ICollection<cliente> cliente { get; set; }
    }
}
