//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_paro
    {
        public tipo_paro()
        {
            this.dias_paro = new HashSet<dias_paro>();
        }
    
        public int id_tipo_paro { get; set; }
        public string nombre { get; set; }
        public Nullable<int> eliminado { get; set; }
    
        public virtual ICollection<dias_paro> dias_paro { get; set; }
    }
}
