//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id_usuario { get; set; }
        public Nullable<int> id_tipo_usuario { get; set; }
        public string nombre { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public Nullable<int> id_empleado { get; set; }
    
        public virtual empleado empleado { get; set; }
    }
}
