//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEnviaMsgsNuevoCredito
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_pregunta_frecuente
    {
        public int id { get; set; }
        public string pregunta { get; set; }
        public string respuesta { get; set; }
        public Nullable<System.DateTime> ultima_modificacion { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<int> eliminado { get; set; }
    }
}
